input_data_path: "data/external/heart.csv"
output_model_path: "models/model.pkl"
output_transformer_path: "models/transformer.pkl"
metrics_path: "models/metrics.json"
splitting_params:
  val_size: 0.1
  test_size: 0.1
  random_state: 42
models_params:
  - model_name: "LinearSVC"
    params:
      penalty: "l2"
      loss: "squared_hinge"
      dual: False
      tol: 0.0001
      C: 0.5
      multi_class: "ovr"
      fit_intercept: True
  - model_name: "SGDClassifier"
    params:
      loss: "hinge"
      penalty: "elasticnet"
      alpha: 0.0001
      l1_ratio: 0.1
      fit_intercept: True
      max_iter: 1000
      shuffle: True
      tol: 0.0001
      random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_feature:
    - "target"