apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
  labels:
    app: fast-api-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fast-api-deployment
  template:
    metadata:
      name: fast-api-deployment
      labels:
        app: fast-api-deployment
    spec:
      containers:
        - image: arhimisha/ml_in_prod_task_2:v1
          name: fast-api
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
